// <auto-generated />
using System;
using BreakAwayMVCWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BreakAwayMVCWebApp.Migrations
{
    [DbContext(typeof(BreakAwayContext))]
    [Migration("20220901182326_PhotoNotRequired")]
    partial class PhotoNotRequired
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BreakAwayMVCWebApp.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinationId"), 1L, 1);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("DestinationId");

                    b.ToTable("Destination");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            Country = "USA",
                            Description = "Eco Tourism at it's best in the exquite Bali",
                            DestinationName = "Indonesia",
                            Photo = new byte[] { 0 }
                        });
                });

            modelBuilder.Entity("BreakAwayMVCWebApp.Models.Lodging", b =>
                {
                    b.Property<int>("LodgingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LodgingId"), 1L, 1);

                    b.Property<bool>("IsResort")
                        .HasColumnType("bit");

                    b.Property<int>("LodgingDestinationId")
                        .HasColumnType("int");

                    b.Property<string>("LodgingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LodgingId");

                    b.HasIndex("LodgingDestinationId");

                    b.ToTable("Lodging");
                });

            modelBuilder.Entity("BreakAwayMVCWebApp.Models.Lodging", b =>
                {
                    b.HasOne("BreakAwayMVCWebApp.Models.Destination", "LodgingDestination")
                        .WithMany("Lodgings")
                        .HasForeignKey("LodgingDestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LodgingDestination");
                });

            modelBuilder.Entity("BreakAwayMVCWebApp.Models.Destination", b =>
                {
                    b.Navigation("Lodgings");
                });
#pragma warning restore 612, 618
        }
    }
}
